name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.x.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/
    - uses: codecov/codecov-action@v1
      with:
        token: 0269b2c2-d780-44c4-9525-8e464d79202f # not required for public repos
        files: ./FlyPuzzle.Tests/TestResults/coverage.opencover.xml
        flags: unittests 
        name: codecov-umbrella
        fail_ci_if_error: true 
        verbose: true
